### ISSUE TITLE
flakiness on electron

### ISSUE THREAD

**Issue by substack** [digidem/ecuador-map-editor#10]
ideditor is much flakier on electron than in a browser:

* mouse updates stop registering when creating a shape after some distance
* tiles don't load in the right and lower corners of the view pane

Maybe on Mac and windows it's different, but on linux everything is fairly flaky.

**Comment by gmaclennan** [comment]
I have a suspicion that this might be related to how the electron window is currently created, and creating a static file server to get it working. This is how I implemented the mining imagery electron app:

https://github.com/digidem/rupununi-mining/blob/offline/index.js

One thing I noticed is the `electron` package on npm is something different, should be `electron-prebuilt`.

**Comment by substack** [comment]
Good catch. Swapping `electron` for `electron-prebuilt` fixed the flakiness.
