### ISSUE TITLE
area of interest landsat script

### ISSUE THREAD

**Issue by substack** [digidem/ecuador-map-editor#12]
This script could pull down data with the `landsat` command for all imagery within certain extents and put them into `public/tiles`.

**Comment by gmaclennan** [comment]
I have downloaded Sentinel-2 data from https://scihub.copernicus.eu/s2/#/home which is fantastic new 10m resolution multi-spectral imagery. I used the new [Sentinel 2 Driver in GDAL 2.1](http://www.gdal.org/frmt_sentinel2.html) to process the data into tifs of the 10m bands, then extracted an area of interest with just RGB bands, and used ImageMagick to correct the color:

```sh
convert -channel RGB -normalize -modulate 120,150 -gamma 1.8 10m-crop.tif
```

I followed [these instructions](https://www.mapbox.com/help/processing-satellite-imagery/) to re-georeference processed data and guide some of the color adjustments.

I used [tilemill[(https://github.com/mapbox/tilemill/) to convert the TIF into mbtiles, then [tl](https://github.com/mojodna/tl) to copy from mbtiles to an `z/x/y` image folders.

I have found [landsat-util](https://github.com/developmentseed/landsat-util) to be very useful for downloading and processing landsat imagery, and http://libra.development-seed.org/ to be great for browsing available data.

I think we have the images we need for the work right now, let's work on a more automated process in the future.
